### ISSUE TITLE
Crash on Testfairy 1.6.0 and Appc SDK 5.2.1

### ISSUE THREAD

**Issue by adampax** [testfairy/ti.testfairy#3]
Hi,

I'm trying to add v1.6.0 of the module to an Appcelerator app running Appc SDK 5.2.1, and I am crashing the app when calling `TiTestFairy.begin('api key');`

Reverted to 1.5.7 and the crash stops.  Testing on simulator and device running iOS 9.3.

```
Mar 30 15:41:26 iPhone-6 SpringBoard[63] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Mar 30 15:41:26 iPhone-6 SpringBoard[63] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Mar 30 15:41:26 iPhone-6 securityd[857] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Mar 30 15:41:26 iPhone-6 securityd[857] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Mar 30 15:41:26 iPhone-6 amfid[1298] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Mar 30 15:41:26 iPhone-6 kernel[0] <Notice>: xpcproxy[1373] Container: /private/var/mobile/Containers/Data/Application/75488E73-5C02-4105-B627-A0F2E18F2FD6 (sandbox)
Mar 30 15:41:27 iPhone-6 SUP[1373] <Warning>: [INFO] [object ComTestfairyTitestfairyModule] loaded
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 1   0x1857b8654 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 2   0x181558fe4 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 3   0x18154de50 _os_once
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 4   0x181556728 pthread_once
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 5   0x186742d98 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 6   0x186742680 WebKitInitialize
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 7   0x186ce7fa0 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 8   0x18133d47c <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 9   0x18133e2c0 dispatch_once_f
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 10  0x180f58fc8 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 11  0x180f58d00 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 12  0x180f5f8b8 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 13  0x180f69d78 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 14  0x1004c6070
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 15  0x1004bcbbc
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 16  0x1004c5ae8
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 17  0x18133d47c <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 18  0x18133e2c0 dispatch_once_f
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 19  0x1004c5ac0
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 20  0x1004bcc80
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 21  0x1004bcc24
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 22  0x1818f8ae0 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 23  0x1817f0548 <redacted>
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 24  0x1000fc91c
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 25  0x1000fb9d0
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 26  0x1002c69fc
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 27  0x1003619fc
Mar 30 15:41:27 iPhone-6 SUP[1373] <Notice>: 28  0x100367938
Mar 30 15:41:27 iPhone-6 SpringBoard[63] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Mar 30 15:41:27 iPhone-6 mediaserverd[28] <Notice>: '' com.myproject.app(pid = 1373) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Mar 30 15:41:27 iPhone-6 diagnosticd[975] <Error>: error evaluating process info - pid: 1373, puniqueid: 1373
Mar 30 15:41:27 iPhone-6 mediaserverd[28] <Notice>: 'FigPlayer - 873' (pid = 873) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Mar 30 15:41:27 iPhone-6 com.apple.xpc.launchd[1] (UIKitApplication:com.myproject.app[0xafc6][1373]) <Notice>: Service exited due to signal: Segmentation fault: 11
Mar 30 15:41:27 iPhone-6 locationd[72] <Notice>: need a scan, count, 0, 0, lwatchdog, 0.0, interval, 60.0, needWatchdog, 0
Mar 30 15:41:27 iPhone-6 ReportCrash[1374] <Notice>: Formulating report for corpse[1373] SUP
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: Application 'UIKitApplication:com.myproject.app[0xafc6]' crashed.
Mar 30 15:41:28 iPhone-6 UserEventAgent[26] <Warning>: 3895496618658: id=com.myproject.app pid=1373, state=0
Mar 30 15:41:28 iPhone-6 searchd[1285] <Warning>: ====^^^^ DuetExpert missing data, count -> people:6 applicationDeepLinks:0 applications:8 requests:9 missingAllDataRequests:0
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: Unable to get short BSD proc info for 1120: No such process
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Mar 30 15:41:28 iPhone-6 SpringBoard[63] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
```

**Comment by OliverShanahan** [comment]
Experiencing the same issue with the same versions. Rolling back to 1.5.7 of the testfairy SDK solves the issue.

**Comment by gmegidish** [comment]
Hey guys.

We're working on getting 1.7.0 to Titanium as well. Unfortunately, Titanium has changed the makefiles and now the sdk no longer compiles. But we're working on it. I'll post here when it's working.

**Comment by gmegidish** [comment]
We have released 1.7.0. Can you please download it and give it a try? It fixes two race-conditions that were in 1.6.0 and I'd like to hear it's working great for you.

Please keep me updated.

**Comment by OliverShanahan** [comment]
Problem continues in 1.7 :<

**Comment by adampax** [comment]
Tested 1.7.0 on 9.3 simulator and still crashes when the module loads.

**Comment by nitrag** [comment]
1.6+ giving me issues as well, here's the error from the device logs:

```
  3 15:55:44 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:55:44 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:55:52 Katies-iPhone com.apple.CDScheduler[23] <Error>: Thermal pressure state: 0 Memory pressure state: 0
Apr  3 15:56:03 Katies-iPhone com.apple.Safari.SafeBrowsing.Service[524] <Error>: tcp_connection_handle_connect_conditions_bad 8 failed: 6 - Interface type 'cellular' is prohibited by parameters
Apr  3 15:56:03 Katies-iPhone geocorrectiond[810] <Warning>: /BuildRoot/Library/Caches/com.apple.xbs/Sources/Maps/Maps-1906.50/iOS/geocorrectiond/MCAddressCorrector.m:79 0x12e606930 _primaryAccount = 9F42C679-6EEC-4561-87F9-F75E9422904D personID = 1631918758 mapsToken = AQAAAABW_902-l_skB_Kg21TlNZYta6vbumDXeQ~
Apr  3 15:56:03 Katies-iPhone geocorrectiond[810] <Warning>: /BuildRoot/Library/Caches/com.apple.xbs/Sources/Maps/Maps-1906.50/iOS/geocorrectiond/MCAddressCorrector.m:120 0x12e606930 startProcessing - failed. Too early. LastRunTime 481170148.445921 CurrentTime 481406163.903084 shouldRunAfter 481774948.445921
Apr  3 15:56:04 Katies-iPhone routined[29] <Notice>: 481406164.280013 (4/3/16, 3:56:04 PM EDT), [STATE MODEL]: Cannot archive while processing raw locations
Apr  3 15:56:04 Katies-iPhone routined[29] <Notice>: 481406164.428288 (4/3/16, 3:56:04 PM EDT), [STATE MODEL]: Cannot archive while processing raw locations
Apr  3 15:56:35 Katies-iPhone locationd[60] <Notice>: NETWORK: query, cells, 0, 0, 0, 0, wifis, 1
Apr  3 15:56:38 Katies-iPhone SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Apr  3 15:56:38 Katies-iPhone SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Apr  3 15:56:39 Katies-iPhone kernel[0] <Notice>: xpcproxy[811] Container: /private/var/mobile/Containers/Data/Application/E4A6E0A4-3629-49BB-A7E7-E2AD1A6C074B (sandbox)
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Warning>: [INFO] [object DkNappUiModule] loaded
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Warning>: [INFO] [object DkNappDrawerModule] loaded
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Warning>: [INFO] [object ComTestfairyTitestfairyModule] loaded
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 1   0x185890654 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 2   0x181630fe4 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 3   0x181625e50 _os_once
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 4   0x18162e728 pthread_once
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 5   0x18681ad98 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 6   0x18681a680 WebKitInitialize
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 7   0x186dbffa0 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 8   0x18141547c <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 9   0x1814162c0 dispatch_once_f
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 10  0x186c877f0 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 11  0x181030fc8 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 12  0x181030d00 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 13  0x1810378b8 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 14  0x181041d78 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 15  0x100817b48
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 16  0x10080dc24
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 17  0x1008174ec
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 18  0x18141547c <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 19  0x1814162c0 dispatch_once_f
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 20  0x1008174c4
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 21  0x10080dce8
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 22  0x10080dc8c
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 23  0x1819d0ae0 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 24  0x1818c8548 <redacted>
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 25  0x100099780
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 26  0x100098844
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 27  0x100613960
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 28  0x1006ae960
Apr  3 15:56:39 Katies-iPhone Offroad[811] <Notice>: 29  0x1006b4898
Apr  3 15:56:39 Katies-iPhone mediaserverd[25] <Notice>: '' com.eagledevelopers.offroad(pid = 811) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Apr  3 15:56:39 Katies-iPhone diagnosticd[84] <Error>: error evaluating process info - pid: 811, puniqueid: 811
Apr  3 15:56:39 Katies-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.eagledevelopers.offroad[0x6388][811]) <Notice>: Service exited due to signal: Segmentation fault: 11
Apr  3 15:56:39 Katies-iPhone mediaserverd[25] <Notice>: 'FigPlayer - 31' (pid = 31) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Apr  3 15:56:39 Katies-iPhone ReportCrash[812] <Notice>: Formulating report for corpse[811] Offroad
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: Application 'UIKitApplication:com.eagledevelopers.offroad[0x6388]' crashed.
Apr  3 15:56:39 Katies-iPhone UserEventAgent[23] <Warning>: 2113876141891: id=com.eagledevelopers.offroad pid=811, state=0
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:56:39 Katies-iPhone SpringBoard[54] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.
Apr  3 15:56:39 Katies-iPhone ReportCrash[812] <Warning>: Saved type '109(109_Offroad)' report (4 of max 25) at /var/mobile/Library/Logs/CrashReporter/Offroad-2016-04-03-155639.ips
```

**Comment by abdielou** [comment]
Exact same thing here: 
Ti SDK 5.2.2
TestFairy 2.0.0

Have only tested iOS. Will soon post if it works for Android.

**Comment by abdielou** [comment]
Works wonderful with Android :)

**Comment by vijaysharm** [comment]
Hi, is this still happening with v2.1.1?
https://github.com/testfairy/ti.testfairy/releases/tag/2.1.1

**Comment by adampax** [comment]
@vijaysharm tested 2.1.1 on Simulator v10.3 and Titanium SDK v6.0.3 and did not get a crash 👍

**Comment by adampax** [comment]
@vijaysharm however, it looks like 2.1.1 for Android was built using the pre- Ti 6.0 sdk, and won't run on the newer sdk.   

See [upgrading android modules for Titanium SDK 6.x](https://medium.com/all-titanium/rebuilding-android-modules-for-titanium-6-x-b20086c5cb47)
Also see this [bug on updating Android modules](https://jira.appcelerator.org/browse/TIMOB-23502)
